[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hydropy"
version = "0.1.0"
dependencies = [
    "jax",
    "jaxlib",
    "numpy",
]
requires-python = ">=3.8"

